# Generated by Django 3.2.15 on 2022-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_classsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsubject',
            name='class_subject',
            field=models.CharField(max_length=50),
        ),
    ]
