# Generated by Django 3.2.15 on 2022-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_classsubject_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_catalog_number',
            field=models.CharField(default='0', max_length=9),
        ),
        migrations.AddField(
            model_name='post',
            name='class_subject',
            field=models.CharField(default='CS', max_length=9),
        ),
    ]
