# Generated by Django 3.2.15 on 2022-10-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20221023_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
