# Generated by Django 3.2.15 on 2022-10-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
