# Generated by Django 3.2.15 on 2022-10-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='associated_dept',
            field=models.ManyToManyField(related_name='_testapp_post_associated_dept_+', to='testapp.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
