# Generated by Django 3.2.15 on 2022-11-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_auto_20221101_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course_id',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
