# Generated by Django 3.2.15 on 2022-11-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_post_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_isbn',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_id',
            field=models.CharField(default='', max_length=4),
        ),
    ]
