# Generated by Django 3.2.15 on 2022-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_auto_20221120_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='subject_text',
            field=models.CharField(default='No subject', max_length=500),
        ),
    ]
