# Generated by Django 3.2.15 on 2022-12-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_post_post_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sell_status',
        ),
    ]
